server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314
    url:  jdbc:mysql://localhost:3306/netsafe?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml